# Install a collection from Ansible Galaxy.
- name: cisco.ios
  version: 2.6.0
  source: https://galaxy.ansible.com

# Install a collection from Ansible Galaxy.
- name: ansible.netcommon
  version: 2.5.0
  source: https://galaxy.ansible.com
